#Use the new container-based infrastructure
sudo: false

#Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32stdc++6

#Set the build environment
env:
    - SMVERSION=1.8
    - SMVERSION=1.9

#And compile!
install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
before_script:
# TODO Import other modules to compilation
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - mkdir compiled
    - mkdir compiled/MyJailbreak
script: ./compile.sh MyJailbreak/catch.sp MyJailbreak/cowboy.sp MyJailbreak/dealdamage.sp MyJailbreak/drunk.sp MyJailbreak/duckhunt.sp MyJailbreak/ffa.sp MyJailbreak/freeday.sp MyJailbreak/hebattle.sp MyJailbreak/hide.sp MyJailbreak/hud.sp MyJailbreak/knife.sp MyJailbreak/lastguard.sp MyJailbreak/menu.sp MyJailbreak/myjailbreak.sp MyJailbreak/noscope.sp MyJailbreak/playertags.sp MyJailbreak/ratio.sp MyJailbreak/request.sp MyJailbreak/suicide.sp MyJailbreak/torch.sp MyJailbreak/war.sp MyJailbreak/warden.sp MyJailbreak/weapons.sp MyJailbreak/zeus.sp MyJailbreak/zombie.sp


#Notifications
notifications:
    email: false
